/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicInfo: typeof import('./src/components/card/basicInfo/BasicInfo.vue')['default']
    Button: typeof import('./src/components/elements/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Info: typeof import('./src/components/card/basicInfo/Info.vue')['default']
    Input: typeof import('./src/components/elements/Input.vue')['default']
    Inspiration: typeof import('./src/components/card/abilities/Inspiration.vue')['default']
    Name: typeof import('./src/components/card/basicInfo/Name.vue')['default']
    Navbar: typeof import('./src/components/elements/Navbar.vue')['default']
    PassivePerception: typeof import('./src/components/card/abilities/PassivePerception.vue')['default']
    Proficiency: typeof import('./src/components/card/abilities/Proficiency.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingThrow: typeof import('./src/components/card/abilities/savingThrows/SavingThrow.vue')['default']
    SavingThrows: typeof import('./src/components/card/abilities/savingThrows/SavingThrows.vue')['default']
    Sidebar: typeof import('./src/components/elements/Sidebar.vue')['default']
    SingleStat: typeof import('./src/components/card/stats/SingleStat.vue')['default']
    Skill: typeof import('./src/components/card/abilities/skills/Skill.vue')['default']
    Skills: typeof import('./src/components/card/abilities/skills/Skills.vue')['default']
    StatList: typeof import('./src/components/card/stats/StatList.vue')['default']
  }
}
